import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/providers/QueryProvider";
import { ChildrenProps } from "@/types/ChildrenProps";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<ChildrenProps>) {
  return (
    <html>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className=" min-h-screen">
        <QueryProvider>
          <div className="min-h-screen flex items-center justify-center px-4 sm:px-6 lg:px-8">
            {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
